language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: N1Lzthmuj8p1VXUYffuuLFhW+KsK7FjXMKQg3rTgGK0eHMoX7N7oBggdU+LQYz0mP6zsYou3djc7NngQmkj6pf88KVeC//W/hoSoVdWhR2H6NWewhJKa0ycAG9Axgp4OKAxKvMTHUFeoU8v/Cn79jeNK7UgWpbewsx4iKrB5WkcQyM99xpya6R4tjAGq51ziFDdzeue9WNN2n1YVm84JIPXLQR7zml9bLSpTgXbEMsWyVtbDEQ7UgHNbvnFBcHgP/0QDclueMOgRnMed3Xna3rTy/LM3EAPCSXqIYafqkSHwY1NhKhAY9YEBc5GFv2+hTlERJM9zlkXVGcpjv/6ecjyzG3zXFvqJ6B6yV9QuDHG6vJtftflmGh1bySOFAZVz4CGI2IdVeH5Ad9DqEq1c2bQfS2KLW9szDy/LdF6nN/e64Gn11Gj3aiMyi5E7gnjMpSUiJOZNlWHqtcyQeGiZzsbdqoRBmdNEMygqwReGHxBrp+9ps7LZolXPIWQ2TPd7zDioqEgp+QuoXc8lvRwd+15fnHQFdf/0dl6TdRw8P05v33ki7+DO/LQvywLAoh4LyZNmr9u0mI9OM+EUFGQzJvmKI19DY8M48xoq7LVMamxFYWGBbrTZ00YcC7LDSd7s00y30MB5uS0k12QstuMDpj9I+0wtisN1RWGMAQ6XHdY=
  app: arcane-mesa-11205
  on:
    repo: oscaralexander2125/node-shopping-list-integration-tests
